CREATE TABLE SPILL (
	ID BIGINT NOT NULL PRIMARY KEY,
	STATUS TEXT,
	KORTSTOKK TEXT
);
CREATE SEQUENCE SPILL_ID_SEQ;

CREATE TABLE SPILLER (
    ID BIGINT NOT NULL PRIMARY KEY,
    SPILL_ID BIGINT,
    NAVN TEXT,
    KORT TEXT,
    STAAR BOOLEAN,
    CONSTRAINT FK_SPILLER_SPILL
        FOREIGN KEY(SPILL_ID)
            REFERENCES SPILL(ID)
);
CREATE SEQUENCE SPILLER_ID_SEQ;

CREATE TABLE DEALER (
    ID BIGINT NOT NULL PRIMARY KEY,
    SPILL_ID BIGINT,
    KORT TEXT,
    VISER_ALLE_KORT BOOLEAN,
    CONSTRAINT FK_DEALER_SPILL
        FOREIGN KEY(SPILL_ID)
            REFERENCES SPILL(ID)
);
CREATE SEQUENCE DEALER_ID_SEQ;